# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  identifier="ci"
  name="Classe inversée"
  url="classe_inversee/"
  weight="10"

[[main]]
  name="Présentation de la classe inversée"
  parent="ci"
  url="classe_inversee/"
  weight="10"

[[main]]
  identifier="manim"
  name="Animations manim"
  parent="ci"
  url="classe_inversee/manim/"
  weight="20"

[[main]]
  identifier="quiz"
  name="Questions Moodle"
  parent="ci"
  url="classe_inversee/questions_moodle/"
  weight="30"

[[main]]
  identifier="commentee"
  name="Présentations commentées"
  parent="ci"
  url="classe_inversee/pres_commentee/"
  weight="10"

[[main]]
  name="Les ressources"
  parent="ci"
  url="classe_inversee/ressources_ci"
  weight="40"

[[main]]
  name = "Cycle d'orientation"
  url = "cycle/"
  weight = 30

[[main]]
  name = "Collège"
  url = "college/"
  weight = 30

[[main]]
  name = "Quelques réflexions"
  url = "publication/"
  weight = 40

[[main]]
  name = "Divers"
  identifier="divers"
  url = "divers/"
  weight = 50

[[main]]
  name="Nos héros de l'open source"
  parent="divers"
  url="heros_os"
  weight="10"

[[main]]
  name = "Contact"
  url = "contact/"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
